### ISSUE TITLE
Back-projection Idea

### ISSUE THREAD

**Issue by mkocabas** [facebookresearch/VideoPose3D#1]
Hi, thanks for open sourcing your code for the paper. Leveraging temporal convolutions is a great idea and the results are promising. However, I just want to point out an issue about the back-projection idea. The idea was visited for 3D human pose estimation by 2 previous works (maybe others that I'm not aware of):
- Adversarial Inverse Graphics Networks: Learning 2D-to-3D Lifting and Image-to-Image Translation from Unpaired Supervision ([link](https://arxiv.org/abs/1705.11166)) at CVPR 2017.
- Can 3D Pose be Learned from 2D Projections Alone? ([link](https://arxiv.org/abs/1808.07182)) by @dylandrover et al. at ECCVW 2018.

It'd be nice to mention those great works in your preprint.

Thanks!

**Comment by michaelauli** [comment]
Thanks for your interest and the references! We will discuss the differences to these papers in our next revision. Glancing over the papers, it looks like they use GANs and we do not.
