### ISSUE TITLE
How to just render inferred keypoints?

### ISSUE THREAD

**Issue by ROODAY** [facebookresearch/VideoPose3D#102]
I have some keypoints in the shape (N, 17, 3), and I'd just like to render a video where those keypoints are animated like the reconstruction in the examples, without any input video by the side/any other information. I combined code from run.py and visualization.py, removing code that seemed unnecessary, ending up with this: https://gist.github.com/ROODAY/f11c6951655a7192a50f179de85e9a0f

However, running this with: `python3 animate.py -d h36m -arc 3,3,3,3,3 -c checkpoint --viz-action custom --viz-camera 0 --viz-output new-test.mp4 --viz-size 6` gives me this error:

```
Traceback (most recent call last):
  File "animate.py", line 171, in <module>
    limit=args.viz_limit, downsample=args.viz_downsample, size=args.viz_size, viewport=(cam['res_w'], cam['res_h']))
  File "animate.py", line 41, in render_animation
    ax.set_aspect('equal')
  File "/usr4/cs640/rooday/.local/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 1281, in set_aspect
    'It is not currently possible to manually set the aspect '
NotImplementedError: It is not currently possible to manually set the aspect on 3D axes
```

The line that's complaining about setting aspect is from the original render_animation function so I'm unsure why it's erroring here. Does anyone have some insight?

**Comment by dariopavllo** [comment]
If you don't want to render the video, you can just set `input_video_path` to `None`. The script will render a black video with only the 2D keypoint overlay.

If you don't want to render 2D keypoints at all, you just have to remove the corresponding entry from the input dictionary `poses`, or set `ground_truth` to `None` in run.py.

**Comment by ROODAY** [comment]
Welp that's pretty simple! I ended up just commenting out the offending line about setting aspect and it turned out fine, just rendering the reconstruction I needed. Thanks for the insight though!

**Comment by rhljajodia** [comment]
Hello.
Similar to this, is there any way to run without any visualization at all but instead save it as a .mp4?
I am running the program on a cloud server and they do not offer visualization facility so I keep running into the same error as the original post. I was hoping to save it to an .mp4 instead and download it. I have tried but have not been successful so far.
Thank you.
