### ISSUE TITLE
How to map Detectron and H36M skeletons?

### ISSUE THREAD

**Issue by wishvivek** [facebookresearch/VideoPose3D#11]
I'm trying to test an in-the-wild video, and I already have the 2D keypoints from the Detectron (see image below). My question is, since the Detectron is predicting keypoints that are different from the h36m keypoints (i.e., spine, thorax are not predicted by Detectron, and 5 MS-COCO face keypoints are not there in H36M), how do I map these? Do I have to change something in the Detectron in order to map to the skeleton present in the h36m_dataset.py? Thanks!
![output](https://user-images.githubusercontent.com/16181622/50303339-a63e5900-0441-11e9-87cd-72b85219504e.png)

**Comment by dariopavllo** [comment]
The 2D keypoints and 3D joints don't necessarily need to match. The model will learn to map these if trained to do so.

You can either train/fine-tune Detectron on Human3.6M (using a new set of joints) or train our pose estimation model using COCO keypoints. For the latter, we have already provided a pretrained model: https://s3.amazonaws.com/video-pose-3d/d-pt-243.bin
