### ISSUE TITLE
single-frame model for coco keypoints

### ISSUE THREAD

**Issue by Zeqiang** [facebookresearch/VideoPose3D#114]
Hi, 
Since coco keypoints have different format from h36m format, is it possible that the pose model can accept coco keypoints then predict h36m keypoints?

if so, do u have single frame model for this?

Thanks

**Comment by dariopavllo** [comment]
Hi,

Yes. In fact, some of the pretrained models that we have (especially those for prediction in the wild) map from 2D COCO keypoints to 3D Human3.6M joint positions.

Unfortunately, we don't have a single-frame model, but it should be pretty fast to train it from scratch.
