### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for TemporalModelOptimized1f:

### ISSUE THREAD

**Issue by immkapoor** [facebookresearch/VideoPose3D#117]
I am trying to run this code with Ubuntu 19.10 with cpu only configuration. 
I ran the following command python run.py -k cpn_ft_h36m_dbb -arc 3,3,3 -c checkpoint --evaluate pretrained_h36m_cpn.bin and got the above error.
Is it because I changed the architecture of the model as against the original one . or is it because of using cpu machine? The whole traceback is as below:
Traceback (most recent call last):
  File "run.py", line 209, in <module>
    model_pos_train.load_state_dict(checkpoint['model_pos'])
  File "/home/mk/anaconda3/envs/fb_detectron/lib/python3.6/site-packages/torch/nn/modules/module.py", line 830, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for TemporalModelOptimized1f:
	Unexpected key(s) in state_dict: "layers_conv.4.weight", "layers_conv.5.weight", "layers_conv.6.weight", "layers_conv.7.weight", "layers_bn.4.weight", "layers_bn.4.bias", "layers_bn.4.running_mean", "layers_bn.4.running_var", "layers_bn.5.weight", "layers_bn.5.bias", "layers_bn.5.running_mean", "layers_bn.5.running_var", "layers_bn.6.weight", "layers_bn.6.bias", "layers_bn.6.running_mean", "layers_bn.6.running_var", "layers_bn.7.weight", "layers_bn.7.bias", "layers_bn.7.running_mean", "layers_bn.7.running_var".

**Comment by sach211** [comment]
Were you able to solve this? I'm facing the same issue when I use a different architecture (anything that is not 3,3,3,3,3).
