### ISSUE TITLE
How to inference custom dataset using causal model ?

### ISSUE THREAD

**Issue by Gorosia** [facebookresearch/VideoPose3D#124]
First of all, thanks for this work!

I'm trying to inference in real time.

I read about this :
https://github.com/facebookresearch/VideoPose3D/issues/33

But this is not working on my custom dataset.

Of course I specified --causal flag !

I'll tell you in more detail.

I did it the way it was written in this :
https://github.com/facebookresearch/VideoPose3D/blob/master/INFERENCE.md

`python run.py -d custom -k myvideos -arc 3,3,3,3,3 -c checkpoint --evaluate pretrained_h36m_detectron_coco.bin --render --viz-subject input_video.mp4 --viz-action custom --viz-camera 0 --viz-video /path/to/input_video.mp4 --viz-output output.mp4 --viz-size 6`

The result was pretty much good.

and then I tried to inference using causal model.

`python run.py -d custom -k myvideos -arc 3,3,3,3,3 -c checkpoint --evaluate cpn-ft-243-dbb-causal.bin --causal --render --viz-subject input_video.mp4 --viz-action custom --viz-camera 0 --viz-video /path/to/input_video.mp4 --viz-output output.mp4 --viz-size 6`

But result was terrible. 

Did I miss something? 

Any advice or information would be appreciated!

**Comment by Gorosia** [comment]
I train causal model by my self! so I close this issue.

**Comment by neeek2303** [comment]
@Gorosia hi! Could you please share your causal model?

**Comment by Eric-1216** [comment]
> I train causal model by my self! so I close this issue.

hi! Could you please share your causal model?
