### ISSUE TITLE
Download h36m.zip

### ISSUE THREAD

**Issue by ykamikawa** [facebookresearch/VideoPose3D#137]
https://www.dropbox.com/s/e35qv3n6zlkouki/h36m.zip
I tried to download `h36m.zip` from the above link by following the procedure of `DATASET.md`, but status code 404 is returned.
Thank you for your support.

**Comment by slava-smirnov** [comment]
I'm by no means a provider of this link however as far as I know human36m dataset public distribution is prohibited by it’s licence so I'd not expect the link to work again

**Comment by ykamikawa** [comment]
Thank you for your prompt comment.
I'll contact  the provider:bowing_man:

**Comment by ElegantLin** [comment]
Did you find the dataset? I cannot download it anymore.
