### ISSUE TITLE
Interpolation error in prepare data script

### ISSUE THREAD

**Issue by brunovollmer** [facebookresearch/VideoPose3D#150]
Hey everybody,

I tried to follow the Inference in the Wild part to run the model on a video of mine. When I run step 4 I receive the following error:

`Traceback (most recent call last):
  File "prepare_data_2d_custom.py", line 92, in <module>
    data, video_metadata = decode(f)
  File "prepare_data_2d_custom.py", line 48, in decode
    bb[:, i] = np.interp(indices, indices[mask], bb[mask, i])
  File "<__array_function__ internals>", line 6, in interp
  File "/home/vollmer/anaconda3/envs/pose3d/lib/python3.6/site-packages/numpy/lib/function_base.py", line 1412, in interp
    return interp_func(x, xp, fp, left, right)
ValueError: array of sample points is empty
`

I think it is related to the fact that numpy can't handle the nan values. Does somebody know how to fix this?

**Comment by dariopavllo** [comment]
Looks like there are no detected poses in your file. Try to manually check the output of Detectron to see if poses are actually detected.

**Comment by brunovollmer** [comment]
Thanks. That was it.
