### ISSUE TITLE
Cannot train model with keypoints more than 17

### ISSUE THREAD

**Issue by linwz1997** [facebookresearch/VideoPose3D#154]
I've been trained the model with my own dataset, which has 17 joints like human3.6m has. The training result is good.
However, when I trying to train a model with a dataset contains 21 joints, I got error='nan' in '3d train', '3d train (eval)' and '3d valid (eval)'. After I print out the result of 'predicted_3d_pos', I got the whole ouput value=-inf. 
Do I need to modify the code of  model.py or other ones?

**Comment by dariopavllo** [comment]
As long as the skeleton definition has the correct number of joints, it should work without any changes.
Are you sure you don't have nans/inf in your dataset (or values that are too large)?

**Comment by linwz1997** [comment]
@dariopavllo thanks for your response!
Yes, I found there contains 'nan' in my 2D data, which is the reason why predicted poses become -inf.
After I solve this problem, I can train the model with 21 predicted joints from the 21 keypoints 2D dataset now.
