### ISSUE TITLE
Can't get Poses_D3_Positions_S*.tgz 

### ISSUE THREAD

**Issue by z0978916348** [facebookresearch/VideoPose3D#186]
Can anyone share Poses_D3_Positions_S*.tgz with me?
I have no way to download it because of "Account needs manual verification from the admins. Please be patient which lead to unsuccessful visualization.

Thanks.

**Comment by GuaiYiHu** [comment]
Could you share Poses_D3_Positions_S*.tgz with me?

**Comment by mmahdavian** [comment]
Could you please share them with me too? 
mmahdavi@sfu.ca
