### ISSUE TITLE
Question about focal length normalization

### ISSUE THREAD

**Issue by YxZhxn** [facebookresearch/VideoPose3D#199]
Hi all, I noticed that for Human3.6M, focal length of each camera is normalized ( https://github.com/facebookresearch/VideoPose3D/blob/1afb1ca0f1237776518469876342fc8669d3f6a9/common/h36m_dataset.py#L223 ). Is there any specific reason to do so? Thanks in advance.

**Comment by toBnumber1** [comment]
Hi.so do u know why？
