### ISSUE TITLE
No such file or directory: 'data/data_3d_h36m.npz'

### ISSUE THREAD

**Issue by muhabdulhaq** [facebookresearch/VideoPose3D#208]
If anyone have the the data_2d_h36m_gt.npz and data_3d_h36m.npz file, can you please share to me,
haq-muhammad@ed.tmu.ac.jp

Thank you,

**Comment by HL-HYX** [comment]
If anyone have the the data_2d_h36m_gt.npz and data_3d_h36m.npz file, can you please share to me,
hulong10101@163.com

LongHu@shu.edu.cn

Thank you,

**Comment by IsshikiHugh** [comment]
If anyone have the the data_2d_h36m_gt.npz and data_3d_h36m.npz file, can you please share to me,

3210104319@zju.edu.cn

Thank you,

**Comment by vasudhagrao** [comment]
If anyone have the the data_2d_h36m_gt.npz and data_3d_h36m.npz file, can you please share to me,
vasurao1996@gmail.com

Thank you,
