### ISSUE TITLE
KeyError：‘1.mp4'

### ISSUE THREAD

**Issue by Eric-1216** [facebookresearch/VideoPose3D#210]
when I try to create the output.mp4，something seems to go wrong.
Can I get help？

**Comment by Eric-1216** [comment]
I have solved this problem , so I closed it.

**Comment by shiym2000** [comment]
Hello, how did you solve the problem?

**Comment by cubestudy** [comment]
> Hello, how did you solve the problem?

I have encountered the same problem. Have you solved it

**Comment by yzthhjq** [comment]
我也遇到了相同的问题，请问您是如何解决的
