### ISSUE TITLE
Question about data_2d_humaneva_gt.npz

### ISSUE THREAD

**Issue by Gerrystev** [facebookresearch/VideoPose3D#216]
I inspect data_2d_humaneva_gt.npz generated from prepare_data_humaneva as following:
![git](https://user-images.githubusercontent.com/57003452/154660954-be4897b5-bddc-4c54-a36a-36acc96828f9.png)

I have few question:
1. I read about chunk from the code and issues, from what I understood is chunk is generated because HumanEva has corrupted annotation for a frame, so the video is split into valid chunk. My question is how to know which valid frame is linked to the valid chunk?
2.  Why inside every chunk is split evenly to 3 array (inside red box)? Is it because every video has 3 camera?

**Comment by Gerrystev** [comment]
I think I got it, since the corrupted chunk is separated from valid chunk, I print the corrupted chunk into the .npz file by adding prepare_data_humaneva.py at line 167:
```
if np.isfinite(chunk).all():
    output[subject][name] = np.array(chunk, dtype='float32') / 1000
    output_2d[subject][name] = list(np.array(all_chunks_2d[i], dtype='float32').transpose(1, 0, 2, 3))
else:
    output[subject][name] = np.array(chunk, dtype='float32')
    output_2d[subject][name] = list(np.array(all_chunks_2d[i], dtype='float32').transpose(1, 0, 2, 3))
```

with this, it can link valid frame with valid chunk

As for the 2nd question, yes, it because has 3 camera.

**Comment by lyhsieh** [comment]
3 cameras means 3 RGB cameras, right?
So, is the annotation correct for grayscale cameras? (since 4 grayscale cameras are placed at different placed compared to RGB ones)

**Comment by Gerrystev** [comment]
> 3 cameras means 3 RGB cameras, right?
> So, is the annotation correct for grayscale cameras? (since 4 grayscale cameras are placed at different placed compared to RGB ones)

3 cameras means 3 RGB camera. I only tried the RGB cameras, haven't tried the grayscale one

**Comment by lyhsieh** [comment]
Got it. Thanks a lot!
But I still don't understand what does "chunk" mean and how do I know which valid frame is linked to the valid chunk?

**Comment by Gerrystev** [comment]
> Got it. Thanks a lot! But I still don't understand what does "chunk" mean and how do I know which valid frame is linked to the valid chunk?

The last time I'm using this dataset is last year, some details may be unclear.

So if I remember correctly, chunks mean a series of 3D skeletons coordinates. To know which frame linked to a valid coordinates, before I made a simple program to visualize and sync manually skeleton with the video, then generate it. It should be known that some of the data and video is not sync correctly and there are some delay, that is why I create this program.

I forked and modify something in this dataset to prepare the .npz file. Maybe you can check and experiment from my repo:

https://github.com/Gerrystev/VideoPose3D/tree/main/data

PS: I'm sorry if there is no changelog in my repo because I used this dataset for undergraduate college project.

**Comment by lyhsieh** [comment]
Thanks for your help! But I still got confused, could you please explain a little bit more?
For example, there are totally 861 frames in `S1\Image_data\Box_1_(C4).avi`. However, I read your `data_2d_humaneva15_clean.npz`, there are 29, 133, 39, 81, 86, 7, 98 frames in "Box 1 chunk1" to "Box 1 chunk7" respectively. How are these numbers linked to original  861 frames in  `S1\Image_data\Box_1_(C4).avi`?
Thank you for your help again!

**Comment by Gerrystev** [comment]
> Thanks for your help! But I still got confused, could you please explain a little bit more? For example, there are totally 861 frames in `S1\Image_data\Box_1_(C4).avi`. However, I read your `data_2d_humaneva15_clean.npz`, there are 29, 133, 39, 81, 86, 7, 98 frames in "Box 1 chunk1" to "Box 1 chunk7" respectively. How are these numbers linked to original 861 frames in `S1\Image_data\Box_1_(C4).avi`? Thank you for your help again!

I think it's because after I compared chunks with its corresponding frame manually, I determine some chunks is invalid (e.g. coordinate is out of line from the skeleton) with the frames, so I discard it. Also, I think the author skipped for some frames for synchronization during coordinate generation

https://github.com/facebookresearch/VideoPose3D/blob/main/data/prepare_data_humaneva.py

Maybe this will also help you:
https://github.com/facebookresearch/VideoPose3D/blob/main/DATASETS.md
