### ISSUE TITLE
2d ground truth and data_2d_h36m_cpn_ft_h36m_dbb.npz

### ISSUE THREAD

**Issue by RHnejad** [facebookresearch/VideoPose3D#233]
Hello! :D 

Thank you for the code! I could not quite understand how the code extracts ground truth 2D points from 3D. The tutorial suggested using `cpn_ft_h36m_dbb` specification but this requires `data_2d_h36m_cpn_ft_h36m_dbb.npz`. I followed the code but I could not find any way to create or obtain this file.

**Comment by wwwpkol** [comment]
Hi guy
I also encountered the same problem, is there any other way to solve this problem.

**Comment by jq9898** [comment]
I have the same problem. Have you solved it？

**Comment by Yefkghcs** [comment]
You can find here: https://github.com/facebookresearch/VideoPose3D/blob/main/DATASETS.md#mask-r-cnn-and-cpn-detections

**Comment by Yefkghcs** [comment]
You can find here: https://github.com/facebookresearch/VideoPose3D/blob/main/DATASETS.md#mask-r-cnn-and-cpn-detections

**Comment by Yefkghcs** [comment]
You can find it here: https://github.com/facebookresearch/VideoPose3D/blob/main/DATASETS.md#mask-r-cnn-and-cpn-detections

**Comment by RHnejad** [comment]
> 

Thanks for the answer :)
