### ISSUE TITLE
Maybe MPJPE Protocol #2 is different

### ISSUE THREAD

**Issue by nulledge** [facebookresearch/VideoPose3D#24]
According to your paper, MPJPE protocol-2 is the error after rigid alignment with ground-truth. The definition of rigid alignment is only related with rotation and translation, *not scaling.*

However, I think that your P-MPJPE implementation aligns with rotation, translation *and also scaling.*

Could you tell me which one is correct?

Thanks in advance.

**Comment by dariopavllo** [comment]
Hi,

You are right about the definition, we will clarify it in the next revision of the paper. We align in translation, rotation, and scale. This is consistent with the "Protocol 2" of other approaches, which also align in translation, rotation, and scale.

For reference, see the [implementation of Martinez et al. '17](https://github.com/una-dinosauria/3d-pose-baseline/blob/master/src/predict_3dpose.py#L371) and [Hossain et al. '18](https://github.com/rayat137/Pose_3D/blob/master/temporal_3d_release/temporal_3d.py#L299).

**Comment by nulledge** [comment]
Thank you for the answer.
