### ISSUE TITLE
Multi-angle

### ISSUE THREAD

**Issue by lxy5513** [facebookresearch/VideoPose3D#28]
It is a Great work!  

Could you please tell me weather is it support display the 3D pose in Multi-angle

**Comment by dariopavllo** [comment]
Thanks for your interest in our work!

What do you mean exactly by "multi-angle"? Reconstruction of a pose from multiple cameras (i.e. multiple viewpoints)? If so, our approach is for a single camera, although the general approach can be adapted to other settings.

**Comment by lxy5513** [comment]
Sorry, I can not represent clearly in English. I mean, whether it can see the 3D pose in other orientation.     


the model which feed 2D key points, generates 3D info(coordinate: x, y, depth) ? , I can reconstruct the      
3D pose in other orientation?

**Comment by lxy5513** [comment]
similar to this

![image](https://user-images.githubusercontent.com/39720528/52053005-1dafee00-2593-11e9-9795-188d5b65a88d.png)

**Comment by dariopavllo** [comment]
Yes, you can view the predicted 3D pose under different orientations. Our model outputs (x, y, z) coordinates in the camera coordinate system (meaning that z points towards the camera), but you can freely rotate the pose as you wish.

**Comment by lxy5513** [comment]
Thanks a lot! I really appreciate your reply！
