### ISSUE TITLE
Pretrained model for detectron keypoints (d-pt-243.bin) no longer available for download?

### ISSUE THREAD

**Issue by beatthat** [facebookresearch/VideoPose3D#37]
I had been testing pose estimation on "in the wild" videos following instructions in another issue and using a pretrained model for keypoints generated by Detectron.

The model had been downloadable from here:

https://s3.amazonaws.com/video-pose-3d/d-pt-243.bin

I noticed the change away from S3 storage, and I was hoping the same model would be available here:

https://dl.fbaipublicfiles/video-pose-3d/d-pt-243.bin

...but it seems like it didn't make it along with the migration. 

Can that model be made available again?

**Comment by nng555** [comment]
The URL here is incorrectly typed, the correct URL should be https://dl.fbaipublicfiles.com/video-pose-3d/d-pt-243.bin
