### ISSUE TITLE
the dataset used to train a model performs well in the wild

### ISSUE THREAD

**Issue by bucktoothsir** [facebookresearch/VideoPose3D#4]
The performance on the youtube videos is very good, but I couldn't find any discussions about the wild videos in the paper. 
Could you please introduce more about this part, thank you very much.

**Comment by michaelauli** [comment]
Thanks for your comment! These videos are meant to illustrate that the model also works in settings that are very different from the data it was originally trained on. The method for these videos follows what was done for the other videos.

**Comment by bucktoothsir** [comment]
@michaelauli thanks for your reply!
so you mean that the model trained on human3.6m could also works on youtube videos right?

**Comment by michaelauli** [comment]
yes, we used a model trained on human3.6m to label all videos.
