### ISSUE TITLE
Run for own video

### ISSUE THREAD

**Issue by manansaxena** [facebookresearch/VideoPose3D#48]
Hi, 
I love the work you have done.
How would we run your pre-trained models on my own set of videos to get the output of 3D joint locations?

**Comment by dariopavllo** [comment]
There are a few posts here on how to modify the code to run inference in the wild.
Due to popular demand, we also working on it and will push new code very soon.

**Comment by manansaxena** [comment]
I will look for the post.
Also, is there a way around to make videopose3D work for multi person video.
I just want to get the 3D estimated pose of one person out of many?
Thanks

**Comment by dariopavllo** [comment]
You can do that, but that's independent of our approach. The first step (person bounding box detection in the 2D detector) gives you multiple bounding box proposals, and you should iterate over them.

**Comment by manansaxena** [comment]
Thanks,
Could you please tell where I should make the changes ?
Just a direction would be really helpful.

**Comment by dariopavllo** [comment]
Hi, check out the new pull request:
https://github.com/facebookresearch/VideoPose3D/pull/52

It's not merged yet, but you can already use/adapt it.

**Comment by manansaxena** [comment]
Thanks,
I had some doubts.
1)all the predictions done are in camera space, right ? How to do it in real world co-ordinate system ?
2)what is the location of the root joint as all the predictions are made with it as the origin ?
3)I have the intrinsic and extrinsic camera parameters for my run in the wild video. Where should I input it to make them contribute to the result or how should I pre-process my video with these parameters ?
Thanks
