### ISSUE TITLE
How to keep same sequence size for input 2D and output 3D 

### ISSUE THREAD

**Issue by amin07** [facebookresearch/VideoPose3D#54]
hello,
Thanks for sharing this great work. I was wondering, how did you get the 3D poses of same temporal size as input 2D poses. Say, my input sequence length is 88 and -arch argument is 3, 3, 3; in this case the network will output a sequence of len 62. How did you tackle this during loss calc. did you take only 62 time steps or you padded the input sequence to get a 88 output seq of 3d pose. 
Thanks

**Comment by dariopavllo** [comment]
We just pad the input sequence by replication to ensure that the number of output frames is the same as the number of input frames (before padding).

**Comment by amin07** [comment]
Thanks.
