### ISSUE TITLE
Why need to "qinverse" from the world coordinate to the camera coordinate

### ISSUE THREAD

**Issue by fabro66** [facebookresearch/VideoPose3D#59]
Hi, I really like your work and thank you for providing the source code.

I have a question about the conversion from the world coordinate to the camera coordinate. 
[in common/camera.py](https://github.com/facebookresearch/VideoPose3D/blob/master/common/camera.py)
```
def world_to_camera(X, R, t):
    Rt = wrap(qinverse, R) # Invert rotation
    return wrap(qrot, np.tile(Rt, (*X.shape[:-1], 1)), X - t) # Rotate and translate
```
Why dose need to reverse the quaternions firstly and then convert the world coordinate to the camera coordinate?
Can you tell me what is the meaning of reversing the quaternions?

Best regards.
Fabro

**Comment by fabro66** [comment]
I probably understand why.
The quaternions provided in the code are from the camera coordinate to the world coordinate.Therefore, the quaternions from the world coordinate to the camera coordinate is the transpose of quaternions from the camera coordinates to the world coordinate.The precondition is that the quaternion is a unit quaternion. So the inverse of the quaternions  is equal to the transposition of the quaternions.
Is that right？

**Comment by dariopavllo** [comment]
Correct.

As a side note, the precise terminology here is "conjugate" (changing the sign of all imaginary terms) instead of "transpose", since quaternions are not matrices.

**Comment by fabro66** [comment]
Thank you for your criticism. I confused the matrix with the concept of quaternions.

**Comment by codylcs** [comment]
> I probably understand why. The quaternions provided in the code are from the camera coordinate to the world coordinate.Therefore, the quaternions from the world coordinate to the camera coordinate is the conjugate of quaternions from the camera coordinates to the world coordinate.The precondition is that the quaternion is a unit quaternion. So the inverse of the quaternions is equal to the conjugate of the quaternions. Is that right？

大佬，打扰了，human3.6m数据集的四元数为什么是指的从相机坐标系到世界坐标系？哪里明确说了吗？有些困惑，希望指教

**Comment by codylcs** [comment]
> I probably understand why. The quaternions provided in the code are from the camera coordinate to the world coordinate.Therefore, the quaternions from the world coordinate to the camera coordinate is the conjugate of quaternions from the camera coordinates to the world coordinate.The precondition is that the quaternion is a unit quaternion. So the inverse of the quaternions is equal to the conjugate of the quaternions. Is that right？

大佬，打扰了，human3.6m数据集的四元数为什么是指的从相机坐标系到世界坐标系？哪里明确说了吗？有些困惑，希望指教
