### ISSUE TITLE
2D detection results of CPN and Detectron pretrained on COCO for Human3.6M

### ISSUE THREAD

**Issue by garyzhao** [facebookresearch/VideoPose3D#61]
Hi,

Thanks for sharing such a wonderful implementation of your paper.

I am wondering if it is possible to release the 2D detection results of CPN and Detectron pre-trained on COCO for Human3.6M (which is used for reproducing the results of Table 3 in the paper)?

Thanks.

**Comment by dariopavllo** [comment]
https://dl.fbaipublicfiles.com/video-pose-3d/cpn-pt-243.bin (trained on CPN COCO keypoints)
https://dl.fbaipublicfiles.com/video-pose-3d/d-pt-243.bin (trained on Detectron COCO keypoints)
