### ISSUE TITLE
Data generator only support single cpu worker.

### ISSUE THREAD

**Issue by Yedis** [facebookresearch/VideoPose3D#66]
I noticed the data generators only support single cpu worker.
Is it possible to use multi-cpu ?
thanks a lot !

**Comment by dariopavllo** [comment]
Since all the dataset is loaded in memory (and it only consists of 1D sequences, not images or videos), the impact of the data loader is negligible. I don't think you would gain anything in terms of performance.

**Comment by Yedis** [comment]
understood, thx
