### ISSUE TITLE
the run.py problem

### ISSUE THREAD

**Issue by laowangFish** [facebookresearch/VideoPose3D#7]
In the file run.py, the code at the line756 which i think shoulder be the ' if action_name not in all_actions_by_subject[subject]: ' , just a little confused?

**Comment by dariopavllo** [comment]
I think you are right, thanks for pointing this out!

It has no impact on the Human3.6M evaluation, but it should affect the HumanEva evaluation when you specify the subjects manually. We will push an update and update the numbers in the paper in the next revision.

**Comment by michaelauli** [comment]
We verified that this does effect Human3.6M and the differences on Human-Eva do not change our conclusions about our model. We will update the Human-Eva results in the next revision of the paper.

Thanks again for pointing this out!
