### ISSUE TITLE
The waist doesn't move

### ISSUE THREAD

**Issue by HassanAlsamahi** [facebookresearch/VideoPose3D#75]
I've been inferring the code on a deep squats youtube video, and the poses were correctly estimated but in the 3d representation, the waist doesn't move, as if everything is moving towards the waist.... here is the link of the video https://drive.google.com/open?id=1mPjy5jAKSw0tvCx1ED8H-HyuueaiYXia

anyone know why is that happening?

**Comment by dariopavllo** [comment]
This happens because the predicted position is relative to the root joint, i.e. no global trajectory.
You can post-process the poses to "glue" the lowest joint to the floor. Take a look at https://github.com/facebookresearch/VideoPose3D/issues/51

**Comment by HassanAlsamahi** [comment]
> This happens because the predicted position is relative to the root joint, i.e. no global trajectory.
> You can post-process the poses to "glue" the lowest joint to the floor. Take a look at #51

thanks very much it worked
