### ISSUE TITLE
convert 3D joints in the wild to 2D image joints

### ISSUE THREAD

**Issue by wuneng** [facebookresearch/VideoPose3D#77]
Hi, I want to know how to convert 3D joints in the wild to 2D image joints. I get 3D joint positions in camera space and use both project_to_2d and project_to_2d_linear in common/camera.py to get  2d joints.  Neither of them can produce correct results.Demo code is below.

`cam ={}`
`cam['focal_length'] = [508.8486328125, 508.0649108886719]`
`cam['center'] = [1149.6756591796875, 1147.5916748046875]`
`cam['radial_distortion'] = [-0.1942136287689209, 0.2404085397720337, 0.006819975562393665]`
`cam['tangential_distortion'] = [-0.0016190266469493508, -0.0027408944442868233]`
`cam['intrinsic'] = np.concatenate((cam['focal_length'],cam['center'],cam['radial_distortion'],\`
      `cam['tangential_distortion']))`
`pt3d = np.load('joint3d.npy')#3d joints in the wild`
`camera[:] = cam['intrinsic']`
`pt3d = torch.from_numpy(pt3d).double()`
`camera = torch.from_numpy(camera).double()`
`pt2d = project_to_2d_linear(pt3d, camera)`

**Comment by Walter0807** [comment]
Hi I have the same problem. Did you solve it?

**Comment by wuneng** [comment]
我测试了几个相机参数 ，结果都不正确。在github提issue根本没用，需要发邮件给作者才有用吧。

**Comment by Walter0807** [comment]
@wuneng  Maybe you can check this work. https://github.com/mks0601/3DMPPE_ROOTNET_RELEASE

**Comment by wuneng** [comment]
这个我也试过了

**Comment by vicentowang** [comment]
> Hi, I want to know how to convert 3D joints in the wild to 2D image joints. I get 3D joint positions in camera space and use both project_to_2d and project_to_2d_linear in common/camera.py to get 2d joints. Neither of them can produce correct results.Demo code is below.
> 
> `cam ={}` `cam['focal_length'] = [508.8486328125, 508.0649108886719]` `cam['center'] = [1149.6756591796875, 1147.5916748046875]` `cam['radial_distortion'] = [-0.1942136287689209, 0.2404085397720337, 0.006819975562393665]` `cam['tangential_distortion'] = [-0.0016190266469493508, -0.0027408944442868233]` `cam['intrinsic'] = np.concatenate((cam['focal_length'],cam['center'],cam['radial_distortion'],\` `cam['tangential_distortion']))` `pt3d = np.load('joint3d.npy')#3d joints in the wild` `camera[:] = cam['intrinsic']` `pt3d = torch.from_numpy(pt3d).double()` `camera = torch.from_numpy(camera).double()` `pt2d = project_to_2d_linear(pt3d, camera)`

video in the wild use a camera which has a different intrinsic with the human3.6m camera, so can not be projected.
