### ISSUE TITLE
How to normalize cameras for testing a wild video? 

### ISSUE THREAD

**Issue by abhikhanna30** [facebookresearch/VideoPose3D#8]
Hi,
I was testing a wild video using the keypoints extracted from detectron.
In the run.py for evaluating , there is a lot of camera normalization code (specific to h36m 4 subjects).
My doubt was , if we are testing a wild video like you tested in your demo , how do we do that know?

What i understand is  , i should be loading the keypoints using the saved .npz file and directly evaluating after loading the model and skipping everything else in run.py.

**Comment by dariopavllo** [comment]
Hi,

The normalization procedure is straightforward: we just map the image coordinates (e.g. 0-1000 for a 1000x1000 image) to normalized screen coordinates (-1, 1).

This is implemented here:
https://github.com/facebookresearch/VideoPose3D/blob/master/common/camera.py#L14-L18

If you want to use your own videos, you just have to change the camera resolution, e.g.
https://github.com/facebookresearch/VideoPose3D/blob/master/common/h36m_dataset.py#L26-L27

**Comment by abhikhanna30** [comment]
Hi,

Understood. But then when we predict the 3d positions , wont they be in -1,1 frame and then how to unnormalize for visualization? I could not see the unnormalization in your code anywhere.

**Comment by abhikhanna30** [comment]
The camera to world function which is called in evaluate stage is there but still it outputs coordinates which are scaled down.

**Comment by dariopavllo** [comment]
2D and 3D positions are in a different coordinate system. The keypoints are in normalized screen space (-1, 1), whereas the predicted 3D poses are in meters (not necessarily bounded by -1, 1), with the root joint centered on the origin.

To recover the 2D keypoints you need (1) to reapply the trajectory and (2) project using the camera parameters.
The projection function is described in https://github.com/facebookresearch/VideoPose3D/blob/master/common/camera.py#L37-L67 .

In videos in the wild you don't have the trajectory, so you just put the subject to a fixed position.
The code that does this is here: https://github.com/facebookresearch/VideoPose3D/blob/master/run.py#L715-L729

**Comment by abhikhanna30** [comment]
Got it. Thanks!
