### ISSUE TITLE
Some questions about the model

### ISSUE THREAD

**Issue by fabro66** [facebookresearch/VideoPose3D#88]
Hi, I have some questions as follow:

1. Is this model designed by youself? I found that earlier articles already have similar models.
For example: [An Empirical Evaluation of Generic Convolutional and Recurrent Networks
for Sequence Modeling](https://arxiv.org/abs/1803.01271)

2. The parameter of filter widths only supports odd numbers. Have you experimented with other parameters? For example [5, 5, 5]. I have experimented it. it gets the same good as [3, 3, 3, 3, 3].  But the previous gradient fluctuates greatly. 

3. Why is the parameter of batch size set to 1024? It maybe could train and converge quickly, but the final result may be just a local optimal solution. I think smaller batch sizes can be better generalized and could achieve optimal solutions.

Thanks for your great works!

**Comment by Eric-1216** [comment]
Hello,Have you ever known why?
