### ISSUE TITLE
Results on HumanEva are not similar to the results presented in the paper

### ISSUE THREAD

**Issue by simone6666** [facebookresearch/VideoPose3D#98]
Hi, 
When I evaluate your pretrained model "pretrained_humaneva15_detectron.bin" for HumanEva, some results are similar, but more results are far from the paper: 

Evaluating on subject Validate/S1
----Jog----
Test time augmentation: True
Protocol #1 Error (MPJPE): 44.4190922369911 mm
Protocol #2 Error (P-MPJPE): 36.324550650239246 mm
Protocol #3 Error (N-MPJPE): 44.04567112389549 mm
Velocity Error (MPJVE): 8.557976487053745 mm
----------
----Walking----
Test time augmentation: True
Protocol #1 Error (MPJPE): 17.40052235537872 mm
Protocol #2 Error (P-MPJPE): 13.594885492015848 mm
Protocol #3 Error (N-MPJPE): 17.329326890871567 mm
Velocity Error (MPJVE): 2.4937186780317746 mm
----------
----Box----
Test time augmentation: True
Protocol #1 Error (MPJPE): 30.023043385013143 mm
Protocol #2 Error (P-MPJPE): 24.373595054748126 mm
Protocol #3 Error (N-MPJPE): 29.97529539899244 mm
Velocity Error (MPJVE): 3.391719169005118 mm
----------
Protocol #1   (MPJPE) action-wise average: 30.6 mm
Protocol #2 (P-MPJPE) action-wise average: 24.8 mm
Protocol #3 (N-MPJPE) action-wise average: 30.5 mm
Velocity      (MPJVE) action-wise average: 4.81 mm

Evaluating on subject Validate/S2
----Jog----
Test time augmentation: True
Protocol #1 Error (MPJPE): 44.46256905794144 mm
Protocol #2 Error (P-MPJPE): 37.122304240862526 mm
Protocol #3 Error (N-MPJPE): 44.507578015327454 mm
Velocity Error (MPJVE): 8.009079843759537 mm
----------
----Walking----
Test time augmentation: True
Protocol #1 Error (MPJPE): 31.591225415468216 mm
Protocol #2 Error (P-MPJPE): 28.249419604738552 mm
Protocol #3 Error (N-MPJPE): 31.612192591031395 mm
Velocity Error (MPJVE): 3.5604642083247504 mm
----------
----Box----
Test time augmentation: True
Protocol #1 Error (MPJPE): 43.35696498071655 mm
Protocol #2 Error (P-MPJPE): 33.71192341867729 mm
Protocol #3 Error (N-MPJPE): 43.07404482973022 mm
Velocity Error (MPJVE): 6.966017767815858 mm
----------
Protocol #1   (MPJPE) action-wise average: 39.8 mm
Protocol #2 (P-MPJPE) action-wise average: 33.0 mm
Protocol #3 (N-MPJPE) action-wise average: 39.7 mm
Velocity      (MPJVE) action-wise average: 6.18 mm

Evaluating on subject Validate/S3
----Jog----
Test time augmentation: True
Protocol #1 Error (MPJPE): 58.90553196271261 mm
Protocol #2 Error (P-MPJPE): 48.30435290932655 mm
Protocol #3 Error (N-MPJPE): 59.310385336478554 mm
Velocity Error (MPJVE): 10.7546408350269 mm
----------
----Walking----
Test time augmentation: True
Protocol #1 Error (MPJPE): 43.0119866382924 mm
Protocol #2 Error (P-MPJPE): 50.575064568610614 mm
Protocol #3 Error (N-MPJPE): 45.35291639993148 mm
Velocity Error (MPJVE): 3.1728372128821043 mm
----------
----Box----
Test time augmentation: True
Protocol #1 Error (MPJPE): 52.54075303673744 mm
Protocol #2 Error (P-MPJPE): 42.39204650123914 mm
Protocol #3 Error (N-MPJPE): 52.123550325632095 mm
Velocity Error (MPJVE): 7.002358480046193 mm
----------
Protocol #1   (MPJPE) action-wise average: 51.5 mm
Protocol #2 (P-MPJPE) action-wise average: 47.1 mm
Protocol #3 (N-MPJPE) action-wise average: 52.3 mm
Velocity      (MPJVE) action-wise average: 6.98 mm

Is there anything wrong with it? @dariopavllo

**Comment by qiuzhongwei-USTB** [comment]
> Sorry, I guess it's my problem.

Hi, I failed to generate the annotations of HumanEva following the instruction.
could you help me? Or could you be kind to provide me the annotations? Thanks
![image](https://user-images.githubusercontent.com/34059431/74130019-febf4f80-4c1b-11ea-90b2-5170cf396a8e.png)

**Comment by ky66111** [comment]
> > Sorry, I guess it's my problem.
> 
> Hi, I failed to generate the annotations of HumanEva following the instruction.
> could you help me? Or could you be kind to provide me the annotations? Thanks
> ![image](https://user-images.githubusercontent.com/34059431/74130019-febf4f80-4c1b-11ea-90b2-5170cf396a8e.png)

Sorry for reply on closed issue.

I have once met this problem when the humaneva-I dataset was not completely extracted. Perhaps you should check out the data completeness and corresponding directory tree structure.
